version: '3'

services:

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - data-volume:/www/public
    links:
      - web:web

  web:
    command: npm start
    build: ./node
    volumes:
      - ./node/src:/usr/src/app
    ports:
      - "8080:8080"
    links:
      - mongo
    environment:
      - MONGO_DB_URI=mongodb://mongo:27017/buildo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - data-volume:/data/db

volumes:
  data-volume:

  #very small image (125 bytes total) - used just to store data
  #mongodata:
   # image: tianon/true
    #volumes:
     # - /data/db
