version: '3'

services:

  web:
    command: npm start
    build: ./node
    volumes:
      - /usr/src/app
    ports:
      #here you can define the host port if you need another one.
      #"HOST:CONTAINER" please due to YAML number parsing please specify your port mappings as strings.
      - "8080:8080"
    links:
      - mongo
    environment:
      - MONGO_DB_URI=mongodb://mongo:27017/buildo
    image:
      fpagano/buildo-node

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - data-volume:/data/db

volumes:
  data-volume:
